### ISSUE TITLE
Unable to compile from source on MacOS Mojave 

### ISSUE THREAD

**Issue by andrewkadis** [phillipstanleymarbell/sunflower-simulator#49] opened 2019-01-07 14:36 UTC
**Describe the bug**
Ongoing issues with compiling MacOS Mojave on ack-49's office machine. Happens with a clean install.

As instructed, a git diff has been attached along with a screenshot.
![screen shot 2019-01-06 at 08 49 25](https://user-images.githubusercontent.com/43564344/50773694-5e189680-1289-11e9-9a13-24483be51e0f.png)
[git_diff_output.txt](https://github.com/phillipstanleymarbell/sunflower-simulator/files/2733099/git_diff_output.txt)

**Comment by phillipstanleymarbell** [comment] 2019-01-07 14:59
I am not able to reproduce on a clean clone on 10.14.2 (18C54). Can you also include the output of ` git remote -v`?

**Comment by andrewkadis** [comment] 2019-01-07 17:56
[remote_output.txt](https://github.com/phillipstanleymarbell/sunflower-simulator/files/2733741/remote_output.txt)
![screen shot 2019-01-07 at 17 47 43](https://user-images.githubusercontent.com/43564344/50784410-73032300-12a5-11e9-8f2b-5c053bf504ce.png)

**Comment by phillipstanleymarbell** [comment] 2019-01-07 18:25
What about the result of `git diff master origin/master`?

**Comment by phillipstanleymarbell** [comment] 2019-01-07 20:35
Can you also confirm that you installed the prerequisites listed in step 1 of the `README.md` (`libmpc`, `mpfr`, and `gmp`)?

**Comment by phillipstanleymarbell** [comment] 2019-01-12 15:46
Closing this as I cannot reproduce the error.

**Closed by phillipstanleymarbell** 2019-01-12 15:46 UTC
Labels: Bug
